apps/gbook/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
import settings 


urlpatterns = patterns('gbook.views',     
    # gbook & user authorization 
    url(r'^$', 'gbook_view', name='gbook_view'), 
    url(ur'^section/(?P<section>.+)/$', 'gbook_view', name='gbook_view_section'),            
    url(r'^theme/(?P<theme>[a-z,_,0-9]+)/$', 'gbook_view', name='gbook_view_theme'),       
    url(r'^submit/(?P<theme>[a-z,_,0-9]+)/$', 'gbook_submit', name='gbook_submit'), 
    url(r'^submit/answer/(?P<theme>[a-z,_,0-9]+)/$', 'gbook_submit_answer', name='gbook_submit_answer'),     
    url(r'^unregistered/submit/(?P<theme>[a-z,_,0-9]+)/$', 'gbook_submit_unregistered', name='gbook_submit_unregistered'),  
    url(r'^unregistered/submit/answer/(?P<theme>[a-z,_,0-9]+)/$', 'gbook_submit_unregistered_answer', name='gbook_submit_unregistered_answer'),        
    url(r'^edit-theme/(?P<theme_id>\d+)$', 'gbook_edit_theme', name='gbook_edit_theme'),
    url(r'^edit-answer/(?P<answer>[a-z,_,-,-,0-9]+)$', 'gbook_edit_answer', name='gbook_edit_answer'),
    url(r'^delete-theme/(?P<theme>[a-z,_,-,-,0-9]+)$', 'gbook_delete_theme', name='gbook_delete_theme'), 
    url(r'^delete-answer/(?P<answer>[a-z,_,-,-,0-9]+)$', 'gbook_delete_answer', name='gbook_delete_answer'),
    url(r'^search/$', 'gbook_search', name='gbook_search'),         
     # user profile
    url(r'^manage-profile/$', 'gbook_manage_profile', name='gbook_manage_profile'),     
    url(ur'^view-profile/(?P<view_profile>.+)/$', 'gbook_view_profile', name='gbook_view_profile'),
    url(ur'^сhange-password/$','gbook_change_password', name='gbook_change_password'),     
     # private messages 
    url(ur'^send-message/to/(?P<message_to_profile>.+)/$', 'gbook_send_message', name='gbook_send_message'),     
    url(r'^my-private-messages/$', 'gbook_private_messages', name='gbook_private_messages'),
    url(ur'^show-chat/with/(?P<with_profile>.+)/$', 'gbook_show_chat', name='gbook_show_chat'),
     # karma
    url(r'^my-karma/$', 'gbook_my_karma', name='gbook_my_karma'),     
    url(ur'^(?P<karma_delta>[a-z,_,-,-,0-9]+)/to/(?P<to_profile>.+)/$', 'gbook_change_karma', name='gbook_change_karma'),                
     # registration
    url(r'^registration/$', 'gbook_registration', name='gbook_registration'),     
    url(r'^registration/success/$', 'gbook_registration_success', name='gbook_registration_success'), 
    url(r'^registration/confirm/(?P<auth_key>[a-z,0-9]+)/$', 'gbook_registration_confirm', name='gbook_registration_confirm'), 
      # logout
    url(r'^logout/$', 'gbook_log_out', name='gbook_log_out'),     
     # administration
    url(r'^admin/edit-theme/(?P<theme>[a-z,_,-,-,0-9]+)$', 'gbook_admin_edit_theme', name='gbook_admin_edit_theme'),
    url(r'^admin/edit-answer/(?P<answer>[a-z,_,-,-,0-9]+)$', 'gbook_admin_edit_answer', name='gbook_admin_edit_answer'),
    url(r'^admin/delete-theme/(?P<theme>[a-z,_,-,-,0-9]+)$', 'gbook_admin_delete_theme', name='gbook_admin_delete_theme'), 
    url(r'^admin/delete-answer/(?P<answer>[a-z,_,-,-,0-9]+)$', 'gbook_admin_delete_answer', name='gbook_admin_delete_answer'),
    url(r'^admin/up-theme/(?P<theme>[a-z,_,-,-,0-9]+)$', 'gbook_admin_up_theme', name='gbook_admin_up_theme'),
    url(r'^admin/make-private/(?P<theme>[a-z,_,-,-,0-9]+)$', 'gbook_admin_make_private_theme', name='gbook_admin_make_private_theme'), 
    url(r'^admin/make-public/(?P<theme>[a-z,_,-,-,0-9]+)$', 'gbook_admin_make_public_theme', name='gbook_admin_make_public_theme'),       
    url(ur'^admin/manage-profile/(?P<manage_profile>.+)$', 'gbook_admin_manage_profile', name='gbook_admin_manage_profile'), 
    url(ur'^admin/delete-profile/(?P<delete_profile>.+)$', 'gbook_admin_delete_profile', name='gbook_admin_delete_profile'), 
    url(ur'^admin/add-ban/(?P<to_profile>.+)$', 'gbook_admin_add_ban', name='gbook_admin_add_ban'), 
    url(ur'^admin/remove-ban/(?P<to_profile>.+)$', 'gbook_admin_remove_ban', name='gbook_admin_remove_ban'),   
    url(r'^admin/answers-from-unregistered/$', 'gbook_admin_answers_from_unregistered', name='gbook_admin_answers_from_unregistered'), 
    url(r'^admin/manage-users/$', 'gbook_admin_manage_users',name='gbook_admin_manage_users'),      
)
         

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import patterns, include, url
import settings 


urlpatterns = patterns('',
    url(r'^$', 'gbook.views.index'),
    # etc
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),    
)

# gbook
urlpatterns += patterns('',
    (r'^gbook/', include('gbook.urls')),) 

#captcha    
urlpatterns += patterns('',
    url(r'^captcha/', include('captcha.urls')),)


         

apps/gbook/models.py
# -*- coding: utf-8 -*-
import datetime

from django.db import models
from django.contrib.auth.models import User 
from django.forms import ModelForm, Textarea
from django.db.models.signals import post_init, post_save
from django.utils.translation import ugettext_lazy as _


GENDER_CHOICES = (
(_(u'M'), _(u'Male')),
(_(u'F'), _(u'Female')),
)
 
class GbookProfile(models.Model): 
    user = models.OneToOneField(User) 
    avatar = models.ImageField(blank=True, null=True, upload_to='gbook/avatar/') 
    gender = models.CharField(blank=True, null=True, max_length=1,choices=GENDER_CHOICES) 
    city = models.CharField(blank=True, null=True, max_length=30) 
    about = models.CharField(blank=True, null=True, max_length=200) 
    personal_status = models.CharField(blank=True, null=True, max_length=500) 
    karma = models.IntegerField(default=1) 
    karma_points = models.IntegerField(default=1)  
    karma_points_last_add = models.DateTimeField(blank=True, null=True, default=datetime.datetime.now)     
    auth_key = models.CharField(blank=True, max_length=50) 
    banned = models.BooleanField(default=False) 
    banned_by = models.CharField(blank=True, null=True, max_length=50) 
    banned_to = models.DateTimeField(blank=True, null=True)


# create first profile (when install)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        GbookProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

# manage profile karma and ban time
def manage_profile(sender, **kwargs):

    profile = kwargs['instance']

    datetime_now = datetime.datetime.now() 
    
    # if user banned
    if profile.banned and profile.banned_to:
        if profile.banned_to <= datetime_now: # after exit from ban           
            profile.banned = False
            profile.banned_to = None
            profile.banned_by = None
            
            if profile.karma < 1:
                profile.karma = 1 

            profile.save()      
                                  
    # every 3 days activity user get 3 karma points
    add_karma_period = datetime.timedelta(days=3)
    if (datetime_now - profile.karma_points_last_add) > add_karma_period:
        karma_points = profile.karma_points + 3 # increase karma points to 3             
        profile.karma_points = karma_points
        profile.karma_points_last_add = datetime_now
        profile.save()
    
post_init.connect(manage_profile, sender=GbookProfile)
                            


class UsersOnline(models.Model): 
    username = models.CharField(max_length=30) 
    time = models.DateTimeField() # time last request to gbook 
    ip_adress = models.IPAddressField(blank=True, null=True) # current ip               
    
                                                   
class Theme(models.Model):
    theme_start_user = models.CharField(max_length=30)
    theme_start_datetime = models.DateTimeField() 
    theme_start_message_text = models.CharField(max_length=4000)  
    theme_changetime = models.DateTimeField() 
    section = models.CharField(max_length=30,default='',blank=True)    
    private = models.BooleanField(default=False, blank=True)   
    fk_to_profile = models.ForeignKey(GbookProfile,blank=True, null=True)            
    def __unicode__(self):
            return '%s %s %s' % (self.theme_start_user, self.theme_start_datetime, self.theme_start_message_text, self.theme_changetime)               
    class Meta:
        ordering = ('-theme_changetime',) 
                          
class ThemeAnswers(models.Model):
    theme_answer_user = models.CharField(max_length=30)
    theme_answer_datetime = models.DateTimeField()
    theme_answer_message_text = models.CharField(max_length=4000)
    fk_to_theme = models.ForeignKey(Theme, blank=True, null=True)  
    fk_to_profile = models.ForeignKey(GbookProfile,blank=True, null=True)  
    def __unicode__(self):
            return '%s %s %s %s' % (self.theme_answer_user, self.theme_answer_datetime, self.theme_answer_message_text)    

class AnswersFromUnregistered(models.Model):
    unregistered_user = models.CharField(max_length=30)   
    unregistered_user_has_password = models.CharField(max_length=30,blank=True, null=True)                         
    unregistered_user_send_message = models.CharField(max_length=4000)
    unregistered_message_to_theme = models.CharField(max_length=30)
    unregistered_message_section = models.CharField(max_length=30,default='',blank=True)   
    unregistered_user_need_registration = models.CharField(max_length=8,blank=True, null=True)
    unregistered_user_email = models.CharField(max_length=48,blank=True, null=True)    
    unregistered_message_send_time = models.DateTimeField() 
    class Meta:
        ordering = ('-unregistered_message_send_time',)        
      
class PrivateMessages(models.Model):
    current_profile = models.ForeignKey(GbookProfile)  
    message_from_user = models.CharField(blank=True,max_length=30)
    message_to_user = models.CharField(blank=True,max_length=30)
    message_text = models.CharField(blank=True, null=True, max_length=2000)
    message_status = models.CharField(blank=True,max_length=30)
    message_send_time = models.DateTimeField()
    def __unicode__(self):
            return '%s %s %s %s' % (self.message_from_user, self.message_to_user, self.message_text, self.message_status)
     
class KarmaMessages(models.Model): 
    current_profile = models.ForeignKey(GbookProfile)    
    karma_from_user = models.CharField(blank=True, max_length=30)
    karma_to_user = models.CharField(blank=True, max_length=30)    
    karma_text = models.CharField(blank=True, null=True, max_length=2000)
    karma_delta = models.IntegerField(blank=True)
    karma_send_time = models.DateTimeField() 
    def __unicode__(self):
            return '%s %s %s %s' % (self.karma_from_user, karma_to_user, self.karma_text, self.karma_send_time)
            

          
                   

                 
              




       
                    

templates/gbook/_menu.html
{% load i18n %}

<a href="{% url gbook_view %}"/><img src="{{ MEDIA_URL }}/gbook/img/logotip.png" id="logotip" style="border:0px"></a>    
<br>
{% trans "You login as" %} <b>{{ user.username }}</b><br> 
<div class="menu">
  <a href="{% url gbook_view %}">{% trans "Guestbook" %}</a> 
  <a href="{% url gbook_private_messages %}">{% trans "Personal messages" %}</a>
  {% if new_private_messages.count > 0 %}
      (<b>{{ new_private_messages.count }}</b>)
  {% endif %} 
  <a href="{% url gbook_my_karma %}">{% trans "Karma" %}</a>
  <span style="font-family: Arial Bold; font-size:12px;margin-left:14px;margin-right:14px;">|</span>
  <a href="{% url gbook_manage_profile %}">{% trans "Manage profile" %}</a> 
  <a href="{% url gbook_change_password %}">{% trans "Change password" %}</a>   
  <a href="{% url gbook_log_out %}">{% trans "Exit" %}</a>    
  {% if user.is_superuser %}
  <span style="font-family: Arial Bold; font-size:12px;margin-left:14px;margin-right:14px;">|</span>
  <a href="{% url gbook_admin_answers_from_unregistered %}" style="color:red;">
  {% trans "Messages from unregistered users" %}
  </a>
  {% if new_messages_from_unregistered.count > 0 %}(<b>{{ new_messages_from_unregistered.count }}</b>){% endif %}
   <a href="{% url gbook_admin_manage_users %}" style="color:green;margin-left:7px;">
  {% trans "User list" %}
   </a>
  {% endif %} 
</div> 

templates/gbook/change_password.html
{% extends 'gbook/base.html' %}

{% block content %}
{% load i18n %}

<div class="auth_user">
{% include "gbook/_menu.html" %}
</div>

<table class="etc-table">
    <thead>
        <tr>
            <td>
            {% if pass_change_message %}
               {{ pass_change_message }}
            {% else %}
                {% trans "Change password" %}
            {% endif %}   
            </td>            
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td>
            </td>           
        </tr>
    </tfoot>                
    <tbody> 
      <tr>
        <td id="main-content">
          <form action="" method="post">   
          {% csrf_token %}
            <table>
              <tr>
                <td valign="top"><label for="id_user">{% trans "Current password" %}:</label>{{ form.password }}</td>
                <td valign="center">           
                    {% autoescape off %} 
                    {{ form.password.errors }} 
                    {% endautoescape %}  
                </td>
              </tr> 
              <tr>
                <td colspan=2>
                 <div style="width:155px;height:8px;background-color:#58b9eb;"></div>
                </td>
              </tr>            
              <tr>
                <td valign="top"><label for="id_password">{% trans "New password" %}:</label>{{ form.password_new }}</td>
                <td valign="center">           
                    {% autoescape off %} 
                    {{ form.password_new.errors }} 
                    {% endautoescape %}  
                </td>
              </tr>
              <tr>
                <td valign="top"><label for="id_email">{% trans "Repeat new password" %}:</label>{{ form.password_confirm }}</td>
                <td valign="center">           
                    {% autoescape off %} 
                    {{ form.password_confirm.errors }} 
                    {% endautoescape %}  
                </td>
              </tr>  
            </table>                                           
            <br>        
            <input type="submit" id="submit" value="{% trans "Submit" %}"> 
            <br><br>                                  
          </form>
        </td>  
      </tr>
    </tbody>    
</table>

{% endblock %}



templates/gbook/gbook_submit_answer_unregistered.html
{% extends 'gbook/base.html' %}

{% block js %}

<script type="text/javascript"> 
    var  id ='{{ form.unregistered_user_send_message.auto_id }}'; 
        function bbcode(Tag) {
                var Open='['+Tag+']';
                var Close='[/'+Tag+']';
                var object = document.getElementById(id);
                object.focus();
                if (window.attachEvent && navigator.userAgent.indexOf('Opera') === -1) {                                        
                        var s = object.sel;
                        if(s){                                  
                                var l = s.text.length;
                                s.text = Open + s.text + Close;
                                s.moveEnd("character", -Close.length);
                                s.moveStart("character", -l);                                           
                                s.select();                
                        }
                }   else {                                              
                        var ss = object.scrollTop;
                        sel1 = object.value.substr(0, object.selectionStart);
                        sel2 = object.value.substr(object.selectionEnd);
                        sel = object.value.substr(object.selectionStart, object.selectionEnd - object.selectionStart);                                              
                        object.value = sel1 + Open + sel + Close + sel2;
                        object.selectionStart = sel1.length + Open.length;
                        object.selectionEnd = object.selectionStart + sel.length;
                        object.scrollTop = ss;                                             
                }
                return false;
        }
        function smile(Tag) {
                var Open='['+Tag+']';
                var object = document.getElementById(id);
                object.focus();
                if (window.attachEvent && navigator.userAgent.indexOf('Opera') === -1) {                                        
                        var s = object.sel;
                        if(s){                                  
                                var l = s.text.length;
                                s.text = Open + s.text;
                                s.moveEnd("character", -Close.length);
                                s.moveStart("character", -l);                                           
                                s.select();                
                        }
                }   else {                                              
                        var ss = object.scrollTop;
                        sel1 = object.value.substr(0, object.selectionStart);
                        sel2 = object.value.substr(object.selectionEnd);
                        sel = object.value.substr(object.selectionStart, object.selectionEnd - object.selectionStart);                                              
                        object.value = sel1 + Open + sel + sel2;
                        object.selectionStart = sel1.length + Open.length;
                        object.selectionEnd = object.selectionStart + sel.length;
                        object.scrollTop = ss;                                             
                }
                return false;
        }          
</script>

{% endblock %}

{% block content %}

{% load i18n %}    
{% load bbcode_for_gbook %}

<div class="auth_user">
    <a href="/gbook"/><img src="{{ MEDIA_URL }}/gbook/img/logotip.png" id="logotip" style="border:0px"></a>  
    <br>
    <span style="font-size:11px;color:#555">
    Online:
    {% for online_user in online_users %}
        {% if online_user.username != 'AnonymousUser' %}
            <a href="{% url gbook_view_profile view_profile=online_user.username %}"> {{ online_user.username }}</a>
        {% endif %}
    {% endfor %}
    <br>
    {% trans "Online users and guests" %}: {{ online_users.count }}
    </span>
</div>

<table class="etc-table">
    <thead>
        <tr>                                              
          <td style="padding-top:10px">{% trans "Answer to theme" %} <a href="{% url gbook_view_theme theme=to_theme.id %}">№{{ to_theme.id }} </a>          
          <div class="theme_text">
          {{ to_theme.theme_start_message_text|bbcode:user }}
          </div>         
          <span style="font-size:12px;">{% trans "Message before publication will be checked by administrator" %}</span>
          <br><br>
          </td>        
        </tr>
    </thead>
    <tfoot>
        <tr>
          <td>         
          </td>         
        </tr>
    </tfoot>                
    <tbody>
    <tr>
      <td id="main-content">  
          <form action="" method="post" class="jqtransform" enctype="multipart/form-data">             
          {% csrf_token %}
            <table style="width:1000px;"> 
              <tr>
                <td valign="top"><label for="id_unregistered_user">{% trans "Name" %}:</label></td>
                <td valign="top">{{ form.unregistered_user }}           
                    {% autoescape off %} 
                    {{ form.unregistered_user.errors }} 
                    {% endautoescape %}  
                </td>
              </tr>          
              <tr>
                <td valign="top"><label for="id_unregistered_text">{% trans "Message" %}:</label></td>
                <td valign="top">{{ form.unregistered_user_send_message }}
                    {% autoescape off %} 
                    {{ form.unregistered_user_send_message.errors }} 
                    {% endautoescape %}   
                </td>
              </tr>                              
              <tr>
                <td valign="top"><label for="id_captcha_1">{% trans "Captcha" %}:</label></td>
                <td valign="top">
                <div style="width:300px;">
                  {{ form.captcha }}
                </div>
                <div style="margin-top:15px;">
                    {% autoescape off %} 
                    {{ form.captcha.errors }} 
                    {% endautoescape %}
                </div>    
                </td>
              </tr>                               
              <tr>
                <td valign="top">
                  <label for="id_unregistered_need_registration">
                  {% trans "Registration" %}<br />
                  ({% trans "after administrator approve" %}):
                  </label></td>
                <td valign="top">{{ form.unregistered_user_need_registration }}
                    {% autoescape off %} 
                    {{ form.non_field_errors }}
                    {% endautoescape %}                  
                </td>
              </tr> 
              <tr class="registration" style="display:none">
                <td valign="top">
                    <label for="id_unregistered_user_email">
                    Email <br />
                    ({% trans "if you need registration" %}):
                    </label>
                </td>
                <td valign="top">{{ form.unregistered_user_email }}
                    {% autoescape off %} 
                    {{ form.unregistered_user_email.errors }} 
                    {% endautoescape %}                   
                </td>
              </tr>                                         
            </table> 
            <br>        
            <input type="submit" id="submit" value="{% trans "Submit" %}"> 
            <br><br>         
          </form>               
          <div class="bbcodes">                
              {% include "gbook/_bbcodes.html" %}                      
          </div>
     </td>
   </tr> 
   </tbody> 
     
    <script>
        $(document).ready(function () {   
              $("#id_unregistered_user_need_registration").ready(function() {
              var need_reg = $("#id_unregistered_user_need_registration").val();
              if (need_reg == 'yes') {
                  $(".registration").show()
                }
              else {
                 $(".registration").hide()
              }   
            })
               
              $("#id_unregistered_user_need_registration").change(function() {
              var need_reg = $("#id_unregistered_user_need_registration").val();
              if (need_reg == 'yes') {
                  $(".registration").show()
                }
              else {
                 $(".registration").hide()
              }   
            })
         
            });
    </script>   
     
</table>   
            
{% endblock %}

templates/gbook/show_chat.html
{% extends 'gbook/base.html' %}

{% block css %}
<link type="text/css" href="{{ MEDIA_URL }}/gbook/css/jquery.jscrollpane.css" rel="stylesheet" media="all" />
<link type="text/css" href="{{ MEDIA_URL }}/gbook/css/jquery.jscrollpane.lozenge.css" rel="stylesheet" media="all" />
{% endblock %}

{% block js %}

<script type="text/javascript" src="{{ MEDIA_URL }}/gbook/js/jquery.mousewheel.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}/gbook/js/jquery.jscrollpane.min.js"></script>
<script type="text/javascript" id="sourcecode">
$(function()
{
	$('.scroll-pane').jScrollPane();
	$('.scroll-pane-arrows').jScrollPane(
		{
			showArrows: true,
			horizontalGutter: 10
		}
	);
});
</script>

<script type="text/javascript">
$(function() {
    $("#{{ form.message_text.auto_id }}").focus();
});
</script>

<script type="text/javascript">
function keyDown(e){ 
	if(e.keyCode == 17)
		ctrl = true;
else if(e.keyCode == 13 && ctrl)  {

document.getElementById("submit").click();
 }
}
</script>

<script type="text/javascript"> 
var  id ='{{ form.message_text.auto_id }}'; 
        function bbcode(Tag) {
                var Open='['+Tag+']';
                var Close='[/'+Tag+']';
                var object = document.getElementById(id);
                object.focus();
                if (window.attachEvent && navigator.userAgent.indexOf('Opera') === -1) {                                        
                        var s = object.sel;
                        if(s){                                  
                                var l = s.text.length;
                                s.text = Open + s.text + Close;
                                s.moveEnd("character", -Close.length);
                                s.moveStart("character", -l);                                           
                                s.select();                
                        }
                }   else {                                              
                        var ss = object.scrollTop;
                        sel1 = object.value.substr(0, object.selectionStart);
                        sel2 = object.value.substr(object.selectionEnd);
                        sel = object.value.substr(object.selectionStart, object.selectionEnd - object.selectionStart);                                              
                        object.value = sel1 + Open + sel + Close + sel2;
                        object.selectionStart = sel1.length + Open.length;
                        object.selectionEnd = object.selectionStart + sel.length;
                        object.scrollTop = ss;                                             
                }
                return false;
        }
        function smile(Tag) {
                var Open='['+Tag+']';
                var object = document.getElementById(id);
                object.focus();
                if (window.attachEvent && navigator.userAgent.indexOf('Opera') === -1) {                                        
                        var s = object.sel;
                        if(s){                                  
                                var l = s.text.length;
                                s.text = Open + s.text;
                                s.moveEnd("character", -Close.length);
                                s.moveStart("character", -l);                                           
                                s.select();                
                        }
                }   else {                                              
                        var ss = object.scrollTop;
                        sel1 = object.value.substr(0, object.selectionStart);
                        sel2 = object.value.substr(object.selectionEnd);
                        sel = object.value.substr(object.selectionStart, object.selectionEnd - object.selectionStart);                                              
                        object.value = sel1 + Open + sel + sel2;
                        object.selectionStart = sel1.length + Open.length;
                        object.selectionEnd = object.selectionStart + sel.length;
                        object.scrollTop = ss;                                             
                }
                return false;
        }         
</script> 
 
{% endblock %}
 
{% block content %}
{% load i18n %}
{% load bbcode_for_chat %}
 
<div class="auth_user">
{% include "gbook/_menu.html" %}
</div>

<table class="etc-table">
    <thead>
        <tr>
            <td>
                {% trans "Chat with" %} 
                <a href="{% url gbook_view_profile view_profile=with_user %}">{{ with_user }}</a>: 
                <br /><br />
                <a href="">{% trans "renew chat" %}</a>
            </td>          
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td>
                &nbsp;
            </td>           
        </tr>
    </tfoot>                
    <tbody>
    <tr>
      <td id="main-content">
        <div id="container">
         	<div class="scroll-pane-arrows" style="height:300px;">                             	
      		{% for message in messages %}  
          
              {% if message.message_from_user == user.username %}	
                  <p class="you-send"> <b>{{ message.message_from_user }}</b>
              {% else %}   
                  <p class="you-get"> <b>{{ message.message_from_user }}</b>
              {% endif %}
              
              {{ message.message_text|bbcode }}
              <small>{{ message.message_send_time }}</small></p>
              
          {% endfor %}   				 
    			</div>
    	 </div>	       
      </td>
    </tr> 
    <tr>
     <td id="main-content">
            <form action="" method="post" class="jqtransform" enctype="multipart/form-data">             
                {% csrf_token %}
                 <textarea id="id_message_text" rows="10" cols="84" name="message_text" onkeydown="keyDown(event)" onkeyup="keyUp(event)"></textarea>  
                 {% block form_error_text %} 
                 {% autoescape off %} 
                    {{ form.message_text.errors }}      
                 {% endautoescape %} 
                 {% endblock %} 
                 <br>     
                 <input type="submit" id="submit" value="{% trans "Submit" %}">
                 <br>
                 <b style="background:#eee;padding:6px;position:relative;top:-8px;margin-left:9px;">ctrl+enter</b> 
                 <br><br>         
            </form> 
            
            <div class="bbcodes">                
                {% include "gbook/_bbcodes_chat.html" %}                      
            </div>  
                    
     </td>
    </tr>  
</table>    
           
{% endblock %}